### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by MJLHThomassen-Sorama** [oatpp/oatpp-libressl#5]
Currently, this does not compile on windows due to the heavy usage of linux requirements like <unistd.h> and <fcntl.h>. Since Oatpp base works with Windows out of the box, it would be great to have this module also be windows compatible.

**Comment by lganzzzo** [comment]
Hello @MJLHThomassen-Sorama ,

Please checkout the `windows_support` branch - https://github.com/oatpp/oatpp-libressl/tree/windows_support

Please let me know if this port works for you.

Regards,
Leonid

**Comment by lganzzzo** [comment]
Starting from version `0.19.11` `oatpp-libressl` is easy portable and supports Windows.
Release details - [0.19.11](https://github.com/oatpp/oatpp/releases/tag/0.19.11)
